# Generated by Django 2.1.15 on 2022-05-16 02:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_for_link', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='photos_for_author/%Y/%m/%d/')),
                ('about', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('main_photo', models.ImageField(upload_to='main_photos_for_books/%Y/%m/%d/')),
                ('in_stock', models.BooleanField(default=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('fk_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
                'ordering': ['add_date'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=256)),
                ('tel_number', models.CharField(max_length=13)),
                ('books_for_basket', models.ManyToManyField(related_name='books_for_basket', through='shop.Basket', to='shop.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_for_link', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacteristicsBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('fk_characteristic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Characteristic')),
            ],
            options={
                'verbose_name': 'BOOKS Characteristic',
                'verbose_name_plural': 'BOOKS Characteristics',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguagesBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('fk_language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Language')),
            ],
            options={
                'verbose_name': 'Books language',
                'verbose_name_plural': 'Books languages',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_account', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sale', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='PhotoForBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(upload_to='photos_for_books/%Y/%m/%d/')),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
            ],
            options={
                'verbose_name': 'PHOTO FOR BOOKS',
                'verbose_name_plural': 'PHOTOS FOR BOOKS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoForReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(upload_to='photos_for_review/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('fk_check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Check')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=256)),
                ('review_text', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('fk_buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_for_link', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypesOfDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VersionsBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_books_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books')),
                ('fk_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Version')),
            ],
            options={
                'verbose_name': 'Books version',
                'verbose_name_plural': 'Books versions',
            },
        ),
        migrations.AddField(
            model_name='version',
            name='fk_books_id',
            field=models.ManyToManyField(through='shop.VersionsBooks', to='shop.Books'),
        ),
        migrations.AddField(
            model_name='photoforreview',
            name='fk_books_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Review'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='fk_loyalty_card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.LoyaltyCardType'),
        ),
        migrations.AddField(
            model_name='language',
            name='fk_books_id',
            field=models.ManyToManyField(through='shop.LanguagesBooks', to='shop.Books'),
        ),
        migrations.AddField(
            model_name='check',
            name='books',
            field=models.ManyToManyField(through='shop.Purchase', to='shop.Books'),
        ),
        migrations.AddField(
            model_name='check',
            name='fk_buyers_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Buyer'),
        ),
        migrations.AddField(
            model_name='check',
            name='fk_types_of_delivery_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.TypesOfDelivery'),
        ),
        migrations.AddField(
            model_name='check',
            name='fk_types_of_payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.TypesOfPayment'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='fk_books_id',
            field=models.ManyToManyField(through='shop.CharacteristicsBooks', to='shop.Books'),
        ),
        migrations.AddField(
            model_name='category',
            name='fk_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='books_for_review',
            field=models.ManyToManyField(related_name='books_for_review', through='shop.Review', to='shop.Books'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='fk_loyalty_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.LoyaltyCard'),
        ),
        migrations.AddField(
            model_name='books',
            name='fk_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='basket',
            name='fk_books_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Books'),
        ),
        migrations.AddField(
            model_name='basket',
            name='fk_buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Buyer'),
        ),
        migrations.AlterUniqueTogether(
            name='characteristicsbooks',
            unique_together={('fk_characteristic_id', 'fk_books_id')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name_for_link', 'fk_section_id')},
        ),
    ]
